/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DexCallbackHandlerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "WETH"
      | "algebraSwapCallback"
      | "beamswapV3SwapCallback"
      | "fusionXV3SwapCallback"
      | "pancakeV3SwapCallback"
      | "swapCallback"
      | "uniswapV3SwapCallback"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "algebraSwapCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beamswapV3SwapCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fusionXV3SwapCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pancakeV3SwapCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV3SwapCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "algebraSwapCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beamswapV3SwapCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fusionXV3SwapCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pancakeV3SwapCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV3SwapCallback",
    data: BytesLike
  ): Result;
}

export interface DexCallbackHandler extends BaseContract {
  connect(runner?: ContractRunner | null): DexCallbackHandler;
  waitForDeployment(): Promise<this>;

  interface: DexCallbackHandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  WETH: TypedContractMethod<[], [string], "view">;

  algebraSwapCallback: TypedContractMethod<
    [
      _amount0Delta: BigNumberish,
      _amount1Delta: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  beamswapV3SwapCallback: TypedContractMethod<
    [
      _amount0Delta: BigNumberish,
      _amount1Delta: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  fusionXV3SwapCallback: TypedContractMethod<
    [
      _amount0Delta: BigNumberish,
      _amount1Delta: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  pancakeV3SwapCallback: TypedContractMethod<
    [
      _amount0Delta: BigNumberish,
      _amount1Delta: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  swapCallback: TypedContractMethod<
    [
      _amount0Delta: BigNumberish,
      _amount1Delta: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  uniswapV3SwapCallback: TypedContractMethod<
    [
      _amount0Delta: BigNumberish,
      _amount1Delta: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "WETH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "algebraSwapCallback"
  ): TypedContractMethod<
    [
      _amount0Delta: BigNumberish,
      _amount1Delta: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beamswapV3SwapCallback"
  ): TypedContractMethod<
    [
      _amount0Delta: BigNumberish,
      _amount1Delta: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fusionXV3SwapCallback"
  ): TypedContractMethod<
    [
      _amount0Delta: BigNumberish,
      _amount1Delta: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pancakeV3SwapCallback"
  ): TypedContractMethod<
    [
      _amount0Delta: BigNumberish,
      _amount1Delta: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapCallback"
  ): TypedContractMethod<
    [
      _amount0Delta: BigNumberish,
      _amount1Delta: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "uniswapV3SwapCallback"
  ): TypedContractMethod<
    [
      _amount0Delta: BigNumberish,
      _amount1Delta: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
